int alg(int n, <string> args)
{
    int x = 2;
    int y = 3+4;
    <int> a1 = [5];
    <int> a2 = [3];
    bool b1;
    string abrigo;
    <string> boas = [5];

    x = 3*12;
    a2[0] = 1;
    a2[1] = 2*5;
    a1[3+1] = x;

    abrigo = 'boasmas';

	if true then
    	x = 1 + 3 * 4 / 5 % 3;
    else
    	x = (1+1) ;
	b1 = 3 == 4;

	if true then
    {
       	x = 1 + 3 * 4 / 5 % 3;
    }
    else
    {
        x = (1+1) ;
    	boas[x] = abrigo;
    }

    return 0;
}